test:
  name: Ijazah Contract Performance Test
  description: Testing performance of IjazahContract functions
  workers:
    type: local
    number: 1
  rounds:
    - label: create-ijazah
      description: Create Ijazah certificates
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: workloads/createIjazah.js

    - label: read-ijazah
      description: Read Ijazah certificates
      txNumber: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 2
      workload:
        module: workloads/readIjazah.js

    - label: delete-ijazah
      description: Delete Ijazah certificates
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: workloads/deleteIjazah.js

    - label: create-signature
      description: Create signature
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: workloads/createSignature.js

    - label: read-signature
      description: Read signature
      txNumber: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 2
      workload:
        module: workloads/readSignature.js

    - label: get-active-signature
      description: Get active signature
      txNumber: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 2
      workload:
        module: workloads/getActiveSignature.js

    - label: update-signature
      description: Update signature
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: workloads/updateSignature.js

    - label: delete-signature
      description: Delete signature
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: workloads/deleteSignature.js

monitors:
  resource:
  - module: process
    options:
      interval: 3
      processes: [{ command: 'node', arguments: 'caliper.js', multiOutput: 'avg' }]
