version: "3.7"

volumes:
  peer0.rektor.itk.com:
  peer0.rektor.itk.com-couchdb:

networks:
  fabric_test:
    external: true

services:
  peer0.rektor.itk.com:
    container_name: peer0.rektor.itk.com
    image: hyperledger/fabric-peer:2.5
    environment:
      # Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO

      # Peer specific variables
      - CORE_PEER_ID=peer0.rektor.itk.com
      - CORE_PEER_ADDRESS=peer0.rektor.itk.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.rektor.itk.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.rektor.itk.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.rektor.itk.com:7051
      - CORE_PEER_LOCALMSPID=RektorMSP

      # TLS configuration
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/fabric/tls/ca.crt:/etc/hyperledger/fabric/tls/orderer-ca.crt
      - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - ORDERER_CA=/etc/hyperledger/fabric/tls/orderer-ca.crt

      # CouchDB configuration
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-rektor:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw

      # Operation and metrics
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443

      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/admin-msp

      # BCCSP environment variables
      # - CORE_PEER_BCCSP_DEFAULT=SW
      # - CORE_PEER_BCCSP_SW_HASH=SHA2
      # - CORE_PEER_BCCSP_SW_SECURITY=256

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/rektor.itk.com/peers/peer0.rektor.itk.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/rektor.itk.com/peers/peer0.rektor.itk.com/tls:/etc/hyperledger/fabric/tls
      - peer0.rektor.itk.com:/var/hyperledger/production
      - ./crypto-config/ordererOrganizations/itk.com/tlsca/tlsca.itk.com-cert.pem:/etc/hyperledger/fabric/tls/orderer-ca.crt
      - ./crypto-config/peerOrganizations/rektor.itk.com/users/Admin@rektor.itk.com/msp:/etc/hyperledger/fabric/admin-msp
      # - ./core.yaml:/etc/hyperledger/fabric/core.yaml
    ports:
      - 7051:7051
      - 7052:7052
      - 9443:9443
    networks:
      fabric_test:
        ipv4_address: 172.20.0.8
    extra_hosts:
      - "orderer0.itk.com:172.20.0.2"
      - "orderer1.itk.com:172.20.0.7"
      - "orderer2.itk.com:172.20.0.6"
    depends_on:
      - couchdb-rektor

  couchdb-rektor:
    container_name: couchdb-rektor
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "8984:5984"
    networks:
      fabric_test:
        ipv4_address: 172.20.0.9
    volumes:
      - peer0.rektor.itk.com-couchdb:/opt/couchdb/data
