version: '3.7'

volumes:
  peer0.akademik.itk.com:
  peer0.akademik.itk.com-couchdb:

networks:
  fabric_test:
    external: true

services:
  peer0.akademik.itk.com:
    container_name: peer0.akademik.itk.com
    image: hyperledger/fabric-peer:2.5
    environment:
      # Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      
      # Peer specific variables
      - CORE_PEER_ID=peer0.akademik.itk.com
      - CORE_PEER_ADDRESS=peer0.akademik.itk.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.akademik.itk.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.akademik.itk.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.akademik.itk.com:7051
      - CORE_PEER_LOCALMSPID=AkademikMSP
      
      # TLS configuration
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      
      # CouchDB configuration
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-akademik:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      
      # Operation and metrics
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443

      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/akademik.itk.com/peers/peer0.akademik.itk.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/akademik.itk.com/peers/peer0.akademik.itk.com/tls:/etc/hyperledger/fabric/tls
      - peer0.akademik.itk.com:/var/hyperledger/production
    ports:
      - 7151:7051
      - 7152:7052
      - 9543:9443
    networks:
      fabric_test:
        ipv4_address: 172.20.0.10
    depends_on:
      - couchdb-akademik

  couchdb-akademik:
    container_name: couchdb-akademik
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9984:5984"
    networks:
      fabric_test:
        ipv4_address: 172.20.0.11
    volumes:
      - peer0.akademik.itk.com-couchdb:/opt/couchdb/data
