/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddIjazahModal: typeof import('./src/components/AddIjazahModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    RegisterDialog: typeof import('./src/components/RegisterDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
