version: '3.4'

services:

  ipfs1:
    container_name: ipfs1
    image: ipfs/go-ipfs:release
    ports:
      - "4101:4001" # ipfs swarm 
      - "5101:5001" # ipfs api 
      - "8180:8080" # ipfs gateway 
    volumes:
      - /private/var/services/librum/ipfs/ipfs1:/data/ipfs
    networks:
      - ipfs-network

  cluster1:
    container_name: cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: cluster1
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - "9194:9094" # http api
      - "9195:9095" # proxy api
      - "9196:9096" # cluster swarm, other peers connect via this port
    volumes:
      - /private/var/services/librum/ipfs/cluster1:/data/ipfs-cluster
    networks:
      - ipfs-network
    command:
      - "daemon --bootstrap /ip4/172.18.0.3/tcp/9096/p2p/12D3KooWKEWfcHHVxU8RvExsS4pFRXZnqRyQAhEXEc2vqezf2Gzy"

networks:
  ipfs-network:
    external: true
